### ISSUE TITLE
Notes not deleted when account is deleted

### ISSUE THREAD

**Issue by davidak** [codimd/server#302] opened 2020-03-21 03:19 UTC
This violates GDPR. Users have to be able to delete their personal data!

## Steps to reproduce

1. open https://demo.codimd.org/
2. create new account. easy with "Login with GitHub"
3. create note. leave URL open
4. delete account
5. reload note page. it's still there with no owner

Example: https://demo.codimd.org/n0GaRJYeToqFMuTP94TFWg

## Expected behavior

Actually do what dialog says.

>This will delete your account, all notes that are owned by you and remove all references to your account from other notes.

**Comment by SISheogorath** [comment] 2020-03-21 12:10
This is caused by a missing database migration. I'll provide a fix and a new release until this evening.

Installations that initially started their database using `node app.js` after we introduced the feature and where running database migrations only occasionally are not effected. The good news is that cleanups are easy, since we can simply delete all notes which have no existing reference of `ownerId`.

Thanks for finding this issue.

**Comment by SISheogorath** [comment] 2020-03-21 20:08
I'll move the release to tomorrow, but we got things working. Fix is implemented in master and tested on the demo instance.

I'll release it as soon as one or two more people tested it, to make sure things go smooth. **Big thanks** for finding this bug, I hope were able to handle it properly.

**Comment by ErikMichelson** [comment] 2020-03-21 22:33
I just fixed some eslint errors in the cleanup-script (although we're not linting it in the CI scripts) in #305.

**Comment by InnayTool** [comment] 2020-07-10 18:46
This is fixed in master and will be part of 1.6.1.

**Closed by InnayTool** 2020-07-10 18:46 UTC
Labels: bug
