### ISSUE TITLE
Issues with login

### ISSUE THREAD

**Issue by morpheus-87** [codimd/server#154] opened 2019-08-25 15:55 UTC
I set up the server like documented, started it once for the database migrations, added a user with the script `bin/manage_users` and started the server again.

My `config.json` looks like this:

```json
{
    "test": {
        "db": {
            "dialect": "sqlite",
            "storage": ":memory:"
        }
    },
    "development": {
        "loglevel": "debug",
        "hsts": {
            "enable": false
        },
        "db": {
            "dialect": "sqlite",
            "storage": "./db.codimd.sqlite"
        }
    },
    "production": {
        "domain": "localhost:3000",
        "loglevel": "info",
        "hsts": {
            "enable": false
        },
        "csp": {
            "enable": false
        },
        "db": {
            "username": "root",
            "password": "example",
            "database": "codimd",
            "host": "localhost",
            "port": "3306",
            "dialect": "mysql"
        }
    }
}
```

When I try to login, nothing works as expected. The sign in button is still shown and I can't click on notes to open them.

What am I doing wrong?

**Comment by SISheogorath** [comment] 2019-08-26 07:17
Please try the domain without port. `"domain": "local host",` I guess that's where the issue is coming from.

**Comment by morpheus-87** [comment] 2019-08-26 08:24
Thank you for the hint, but it's only working if I put a reverse proxy like nginx in front of the application.

**Comment by rzari** [comment] 2020-04-06 08:52
Additionally on top of @SISheogorath comments, can you try the following?

- `export CMD_DOMAIN=localhost`
- `export CMD_URL_ADDPORT=true`

**Comment by davidmehren** [comment] 2020-07-09 19:30
As there was no reaction for many months, I'm going to close this. If you still need help, feel free to join us [in our chat](https://riot.im/app/#/room/#codimd:matrix.org).

**Closed by davidmehren** 2020-07-09 19:30 UTC
