### ISSUE TITLE
Slides theme font is overwritten

### ISSUE THREAD

**Issue by hydrargyrum** [codimd/server#489] opened 2020-08-31 17:10 UTC
Reveal.js themes specify fonts, but those fonts do not seem used when in presentation mode. Is it because the `<theme>.css` is specified before `slide.css` and so the `font-family: inherit` rule takes precedence?

**Comment by mrdrogdrog** [comment] 2020-09-02 18:43
We investigated this and it turned out that there is a css rule that overrides the theme font on purpose. We have no idea why because this is very old hackmd code.

**Comment by mrdrogdrog** [comment] 2020-09-02 18:44
Stay tuned. We're on it.

**Comment by davidmehren** [comment] 2020-10-24 10:51
@mrdrogdrog Could you dig anything up?

**Comment by mrdrogdrog** [comment] 2020-10-24 10:57
Yes, sry.

The problem is: The theme fonts aren't included in our bundle. If we disable this rule, then the theme fonts will be loaded from google fonts and this is problematic if you don't want to use CDNs.

**Comment by mrdrogdrog** [comment] 2020-10-24 11:00
Also the font loading from google fonts is disallowed by cross origin rules.

**Comment by davidmehren** [comment] 2020-10-24 11:04
So... we could either try to figure out how to include the fonts into our bundle or live with this bug?

**Comment by mrdrogdrog** [comment] 2020-10-24 11:07
Yes.

**Comment by mrdrogdrog** [comment] 2020-10-24 11:12
Maybe we can solve this bug with 2.0.

**Comment by mrdrogdrog** [comment] 2020-11-07 21:25
IMHO I wouldn't fix this issue for 1.x, because we're already rewriting the reveal.js mode in 2.0. Therefore we can prevent this bug beforehand.

**Comment by davidmehren** [comment] 2020-11-08 12:41
Yeah, I think we have to `wontfix` this for 1.x. Spending a lot of time for a fix seems not worth it, if we rewrite the code anyway.

**Closed by davidmehren** 2020-11-08 12:41 UTC
Labels: bug
