### ISSUE TITLE
Error building codimd server with longtext

### ISSUE THREAD

**Issue by flo-up** [codimd/server#126] opened 2019-06-28 19:39 UTC
Hello,

Trying to build current master, following the guide (), I've got this error:
  ERROR: Migration 20171009121200-longtext-for-mysql.js (or wrapper) didn't return a promise﻿
  [...] npm ERR! CodiMD@1.4.0 start: `sequelize db:migrate && node app.js` 

Steps followed :
* debian 9.9 up-to-date as of this evening
* install nodejs 10.0 LTS using official binary distribution
* install yarn
* install debian stable-packaged postgresql
* git clone https://github.com/codimd/server (2019-06-28, about 18:00 UTC)
* configure database settings properly
* npm start --production

Thank you!

**Comment by bitinerant** [comment] 2019-07-18 09:34
Possible duplicate of [issue #1197 in the HackMD repo](https://github.com/hackmdio/codimd/issues/1197)

**Closed** 2019-08-12 12:40 UTC
Labels: bug
