### ISSUE TITLE
socket.io takes about 10s

### ISSUE THREAD

**Issue by swfangzhang** [codimd/server#325] opened 2020-04-17 12:20 UTC
My environment is 2019 MacBook Pro 15-inch.
I found it takes about 10s to be connected.
How to improve the situation?

**Comment by SISheogorath** [comment] 2020-04-17 12:34
@swfangzhang This can become a rather complex problem, but let's start on a very simple level:

Where do you connect to? A company hosted instance? A instance running on your host? The demo instance?

**Comment by swfangzhang** [comment] 2020-04-17 12:53
> @swfangzhang This can become a rather complex problem, but let's start on a very simple level:
> 
> Where do you connect to? A company hosted instance? A instance running on your host? The demo instance?

It runs on my MacBook,and domain is localhost.And it's not docker or others, just I use forever to make it run background

**Comment by SISheogorath** [comment] 2020-04-17 17:13
Does the error also appear when you run it without forever using `npm start`?

**Comment by swfangzhang** [comment] 2020-04-17 17:30
> Does the problem also appear when you run it without forever using `npm start`?
YES.I use Safari developer tools to observer the 10s long progress.Forever,npm or node directly are same

**Comment by SISheogorath** [comment] 2020-04-17 17:40
Can you reproduce this behavior in another browser, say Chrome or Firefox? Also does it appear when you try to use https://demo.codimd.org?

There are some very old stackoverflow reports which basically report the same problem: https://stackoverflow.com/a/18257039 But given how old they are, I hope they are obsolete.

**Comment by swfangzhang** [comment] 2020-04-18 03:27
Chrome also.And here is the request and response.
`GET ws://localhost:3000/socket.io/?noteId=t8DJDZO8QDWMo1Y1E6ZP_g&EIO=3&transport=websocket&sid=D84YXN7X0rM8YkIEAAAE HTTP/1.1
Host: localhost:3000
Connection: Upgrade
Pragma: no-cache
Cache-Control: no-cache
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.113 Safari/537.36
Upgrade: websocket
Origin: http://localhost:3000
Sec-WebSocket-Version: 13
Accept-Encoding: gzip, deflate, br
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
Cookie: Hm_lvt_a4b6fcf2abe8d4c92f626a3bf966f4b3=1586574409; _ga=GA1.1.349751627.1586574409; connect.sid=s%3AyDpiP9mjhpGYZHJskW9VViY-OHZwEMRr.tj9y3qTJOaGyGSIeIOrBP%2BR%2B9TFmYAEU%2F7M8rbXphJM; loginstate=true; userid=bf48ee6b-68db-45c5-9d63-03e8c70334f7; indent_type=space; space_units=4; keymap=sublime; io=D84YXN7X0rM8YkIEAAAE
Sec-WebSocket-Key: W2VqsfRdGzB6ZU5qhTAioA==
Sec-WebSocket-Extensions: permessage-deflate; client_max_window_bits`

`HTTP/1.1 101 Switching Protocols
Upgrade: websocket
Connection: Upgrade
Sec-WebSocket-Accept: qeLgzq1nuYc95kQivrvN5K1kcVI=
Sec-WebSocket-Extensions: permessage-deflate`

This step(try to build TCP tunnel) takes 9.9s.

**Comment by mrdrogdrog** [comment] 2020-04-18 09:16
I tried to reproduce this problem on my MBP (10.15.3) with chrome, firefox and safari (all latest version ). No problem on localhost or demo.codimd.org.

**Comment by ccoenen** [comment] 2020-04-18 09:21
This is a long shot, but: developer tools often include things to test latency and bandwidth. Is anything like that activated at the moment? 10s delay sounds very odd to me. I haven't seen this anywhere, so far.

**Comment by swfangzhang** [comment] 2020-04-18 13:12
Anyway I reinstall it several times.And it performs good now.Thanks guys.

**Comment by swfangzhang** [comment] 2020-04-18 13:27
Maybe I use the latest release instead of `git clone`?

**Comment by SISheogorath** [comment] 2020-04-18 14:43
We just had [someone hinting](https://matrix.to/#/!ybaSlrrMNLeuoQuUuR:matrix.org/$1587218590218AtenZ:kif.rocks?via=matrix.org&via=tchncs.de&via=kif.rocks), that the latest update of jquery probably causes this issue. Yes, the latest release should not have it.

I'll have a look into this later and try to figure out how and why this happens :)

**Comment by davidmehren** [comment] 2020-04-18 15:46
To quote myself from the chat:

The crash is caused by the call to `dataAttributes.hasOwnProperty()` in https://github.com/twbs/bootstrap/blob/68b0d231a13201eb14acd3dc84e51543d16e5f7e/js/tooltip.js#L223, which breaks in jQuery 3.5 because of https://github.com/jquery/jquery/commit/413ff796ae16611777581e7657cb5ca76c3cfb1d.

Possible solutions: Downgrade to jQuery 3.4.2 or upgrade to Bootstrap 4.x

**Comment by inducer** [comment] 2020-05-24 22:26
Sorry, I'm not meaning to be a pest, but I'd love it if this could get fixed on master. This simple diff does the trick for me, following @davidmehren's advice:

```diff
diff --git a/package.json b/package.json
index d5805cc4..b7200120 100644
--- a/package.json
+++ b/package.json
@@ -53,7 +53,7 @@
     "i18n": "^0.8.3",
     "imgur": "git+https://github.com/hackmdio/node-imgur.git",
     "ionicons": "~2.0.1",
-    "jquery": "^3.5.0",
+    "jquery": "3.4.2",
     "jquery-mousewheel": "^3.1.13",
     "jquery-ui": "^1.12.1",
     "js-cookie": "^2.1.3",
diff --git a/yarn.lock b/yarn.lock
index cb59bb77..5d64acbf 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -5463,10 +5463,10 @@ jquery-ui@^1.12.1:
   resolved "https://registry.yarnpkg.com/jquery-ui/-/jquery-ui-1.12.1.tgz#bcb4045c8dd0539c134bc1488cdd3e768a7a9e51"
   integrity sha1-vLQEXI3QU5wTS8FIjN0+dop6nlE=
 
-jquery@^3.5.0:
-  version "3.5.0"
-  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.5.0.tgz#9980b97d9e4194611c36530e7dc46a58d7340fc9"
-  integrity sha512-Xb7SVYMvygPxbFMpTFQiHh1J7HClEaThguL15N/Gg37Lri/qKyhRGZYzHRyLH8Stq3Aow0LsHO2O2ci86fCrNQ==
+jquery@3.4.2:
+  version "3.4.1"
+  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.4.1.tgz#714f1f8d9dde4bdfa55764ba37ef214630d80ef2"
+  integrity sha512-36+AdBzCL+y6qjw5Tx7HgzeGCzC81MDDgaUP8ld2zhx58HdqXGoBd+tHdrBMiyjGQs0Hxs/MLZTu/eHNJJuWPw==
 
 js-beautify@^1.8.8:
   version "1.10.3"
```
Happy to file a PR if you'd like me to. (If you'd like to use this at home, run `yarn` after applying.)

**Comment by SuperSandro2000** [comment] 2020-05-24 23:57
@inducer Can you test if jquery 3.5.1 fixes this issue? If so we can straight update to that.

**Comment by inducer** [comment] 2020-05-25 03:45
It seems to. Here's the updated diff:
```diff
diff --git a/yarn.lock b/yarn.lock
index cb59bb77..938a46c2 100644
--- a/yarn.lock
+++ b/yarn.lock
@@ -5464,9 +5464,9 @@ jquery-ui@^1.12.1:
   integrity sha1-vLQEXI3QU5wTS8FIjN0+dop6nlE=
 
 jquery@^3.5.0:
-  version "3.5.0"
-  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.5.0.tgz#9980b97d9e4194611c36530e7dc46a58d7340fc9"
-  integrity sha512-Xb7SVYMvygPxbFMpTFQiHh1J7HClEaThguL15N/Gg37Lri/qKyhRGZYzHRyLH8Stq3Aow0LsHO2O2ci86fCrNQ==
+  version "3.5.1"
+  resolved "https://registry.yarnpkg.com/jquery/-/jquery-3.5.1.tgz#d7b4d08e1bfdb86ad2f1a3d039ea17304717abb5"
+  integrity sha512-XwIBPqcMn57FxfT+Go5pzySnm4KWkT1Tv7gjrpT1srtf8Weynl6R273VJ5GjkRb51IzMp5nbaPjJXMWeju2MKg==
 
 js-beautify@^1.8.8:
   version "1.10.3"
```
However, it seems like they're [planning to reintroduce that change in 4.0](https://blog.jquery.com/2020/05/04/jquery-3-5-1-released-fixing-a-regression/).

**Comment by davidmehren** [comment] 2020-05-25 09:43
Maybe @SISheogorath can just push an updated `yarn.lock` to `master`?
Most people probably use our setup script and run with `--pure-lockfile`.

**Comment by SISheogorath** [comment] 2020-05-26 14:27
Done :) If someone who noticed the problem before can please confirm that it's gone now, would be great.

**Comment by inducer** [comment] 2020-05-27 04:14
Appears fixed to me.

**Closed** 2020-05-27 08:36 UTC
Labels: bug
